# Generated by Django 5.1.5 on 2026-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0027_remove_registrationrequest_pin_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='source_language',
            field=models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English'), ('german', 'German'), ('french', 'French'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('dutch', 'Dutch')], default='spanish', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='target_language',
            field=models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English'), ('german', 'German'), ('french', 'French'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('dutch', 'Dutch')], default='german', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemquestionexchange',
            name='source_language',
            field=models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English'), ('german', 'German'), ('french', 'French'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('dutch', 'Dutch')], default='spanish', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemquestionexchange',
            name='target_language',
            field=models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English'), ('german', 'German'), ('french', 'French'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('dutch', 'Dutch')], default='german', max_length=20),
        ),
        migrations.AlterField(
            model_name='saveddialog',
            name='source_language',
            field=models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English'), ('german', 'German'), ('french', 'French'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('dutch', 'Dutch')], default='spanish', max_length=20),
        ),
        migrations.AlterField(
            model_name='saveddialog',
            name='target_language',
            field=models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English'), ('german', 'German'), ('french', 'French'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('dutch', 'Dutch')], default='german', max_length=20),
        ),
        migrations.AlterField(
            model_name='savedtopic',
            name='source_language',
            field=models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English'), ('german', 'German'), ('french', 'French'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('dutch', 'Dutch')], default='spanish', max_length=20),
        ),
        migrations.AlterField(
            model_name='savedtopic',
            name='target_language',
            field=models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English'), ('german', 'German'), ('french', 'French'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('dutch', 'Dutch')], default='german', max_length=20),
        ),
    ]
