# Generated by Django 5.1.1 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0030_saveddialog_proficiency_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialogturn",
            name="clear_audio_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
