# Generated by Django 5.1.5 on 2026-08-12 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0031_dialogturn_clear_audio_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStreakPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_streak_pauses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-end_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LearningStreakProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_started_on', models.DateField()),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('flex_days', models.PositiveSmallIntegerField(default=0)),
                ('qualifying_days_toward_flex', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_streak_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('completed_entry_keys', models.JSONField(blank=True, default=list)),
                ('completed_daily_pool', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('studied', 'Studied'), ('flex', 'Flex'), ('paused', 'Paused'), ('missed', 'Missed')], default='pending', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='learning_dailyprogress_user_date_uniq')],
            },
        ),
    ]
