# Generated by Django 5.1.5 on 2026-08-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0032_learningstreakpause_learningstreakprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylearningprogress',
            name='active_seconds_by_language',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
