# Generated by Django 5.1.5 on 2026-08-16 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0036_pinsetuptoken_useronboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAIUsageLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False)),
                ('daily_text_requests', models.PositiveIntegerField(default=0)),
                ('daily_image_requests', models.PositiveIntegerField(default=0)),
                ('daily_audio_characters', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_ai_usage_limit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('provider', models.CharField(max_length=20)),
                ('feature', models.CharField(max_length=80)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio')], max_length=10)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('usage_units', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('failed_request_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date', 'category'], name='learning_ai_usage_user_day_idx'), models.Index(fields=['date', 'provider'], name='lrn_ai_usage_day_provider_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'provider', 'feature', 'model', 'category'), name='learning_daily_ai_usage_uniq')],
            },
        ),
    ]
