# Generated by Django 5.1.5 on 2026-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0037_useraiusagelimit_dailyaiusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraiusagelimit',
            name='daily_realtime_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
