# Generated by Django 5.1.5 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0041_realtime_minutes_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraiusagelimit",
            name="weekly_elevenlabs_characters",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
