# Generated by Django 5.1.5 on 2026-09-01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0042_useraiusagelimit_weekly_elevenlabs_characters"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTimezonePreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timezone", models.CharField(blank=True, default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="learning_timezone_preference", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
