# Generated by Django 5.0.7 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("learning", "0043_usertimezonepreference")]

    operations = [
        migrations.AddField(
            model_name="useraiusagelimit",
            name="weekly_elevenlabs_music_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
