# Generated by Django 5.1.5 on 2026-09-27 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0045_item_phrase_grammar_catalog_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordFormationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(max_length=20)),
                ('target_language', models.CharField(max_length=20)),
                ('pattern_key', models.CharField(max_length=80)),
                ('repetition_count', models.PositiveIntegerField(default=0)),
                ('interval_days', models.PositiveIntegerField(default=1)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'source_language', 'target_language', 'pattern_key'), name='unique_user_word_pattern')],
            },
        ),
    ]
