from django.urls import path

from .views import (
    AuthLoginView,
    AuthLogoutView,
    AuthMeView,
    AuthRegisterView,
    AuthBootstrapStatusView,
    ContentConfirmView,
    ContentDialogAudioRegenerateView,
    ContentDialogDetailView,
    ContentDialogTurnAudioView,
    ContentDialogsView,
    ContentItemDetailView,
    ContentItemExercisesView,
    ContentItemFunnyImageExerciseView,
    ContentItemMarkLearnedView,
    ContentItemQuestionView,
    ContentItemRefreshWordView,
    ContentItemsView,
    ContentPhraseQuickAddView,
    ContentPreviewView,
    ContentTopicConversationStartView,
    ContentTopicConversationHelpView,
    ContentTopicConversationTurnView,
    ContentTopicConversationUserCorrectionView,
    ContentTopicConversationUserTranslationView,
    ContentTopicContextsView,
    ContentTopicDeleteView,
    ContentWordQuickAddView,
    ContentTopicsView,
    ContentWordsView,
    CompleteDifficultItemView,
    HealthView,
    MarkSeenView,
    OverviewStatsView,
    RestoreSessionItemStateView,
    SessionView,
    SubmitReviewView,
)

urlpatterns = [
    path("health", HealthView.as_view(), name="health"),
    path("auth/login", AuthLoginView.as_view(), name="auth-login"),
    path("auth/bootstrap-status", AuthBootstrapStatusView.as_view(), name="auth-bootstrap-status"),
    path("auth/register", AuthRegisterView.as_view(), name="auth-register"),
    path("auth/logout", AuthLogoutView.as_view(), name="auth-logout"),
    path("auth/me", AuthMeView.as_view(), name="auth-me"),
    path("overview-stats", OverviewStatsView.as_view(), name="overview-stats"),
    path("session", SessionView.as_view(), name="session"),
    path("session/restore-item-state", RestoreSessionItemStateView.as_view(), name="session-restore-item-state"),
    path("review", SubmitReviewView.as_view(), name="review"),
    path("seen", MarkSeenView.as_view(), name="seen"),
    path("difficult-items/complete", CompleteDifficultItemView.as_view(), name="difficult-item-complete"),
    path("content/preview", ContentPreviewView.as_view(), name="content-preview"),
    path("content/confirm", ContentConfirmView.as_view(), name="content-confirm"),
    path("content/dialogs", ContentDialogsView.as_view(), name="content-dialogs"),
    path("content/dialogs/<int:dialog_id>", ContentDialogDetailView.as_view(), name="content-dialog-detail"),
    path("content/dialogs/<int:dialog_id>/audio", ContentDialogAudioRegenerateView.as_view(), name="content-dialog-audio-regenerate"),
    path("content/dialogs/<int:dialog_id>/turns/<int:turn_index>/audio", ContentDialogTurnAudioView.as_view(), name="content-dialog-turn-audio"),
    path("content/items", ContentItemsView.as_view(), name="content-items"),
    path("content/words", ContentWordsView.as_view(), name="content-words"),
    path("content/words/add", ContentWordQuickAddView.as_view(), name="content-word-quick-add"),
    path("content/phrases/add", ContentPhraseQuickAddView.as_view(), name="content-phrase-quick-add"),
    path("content/items/<int:item_id>", ContentItemDetailView.as_view(), name="content-item-detail"),
    path("content/items/<int:item_id>/exercises", ContentItemExercisesView.as_view(), name="content-item-exercises"),
    path(
        "content/items/<int:item_id>/exercises/funny-image",
        ContentItemFunnyImageExerciseView.as_view(),
        name="content-item-funny-image-exercise",
    ),
    path("content/items/<int:item_id>/mark-learned", ContentItemMarkLearnedView.as_view(), name="content-item-mark-learned"),
    path("content/items/<int:item_id>/refresh-word", ContentItemRefreshWordView.as_view(), name="content-item-refresh-word"),
    path("content/items/<int:item_id>/question", ContentItemQuestionView.as_view(), name="content-item-question"),
    path("content/conversation/start", ContentTopicConversationStartView.as_view(), name="content-topic-conversation-start"),
    path("content/conversation/help", ContentTopicConversationHelpView.as_view(), name="content-topic-conversation-help"),
    path("content/conversation/turn", ContentTopicConversationTurnView.as_view(), name="content-topic-conversation-turn"),
    path(
        "content/conversation/user-translation",
        ContentTopicConversationUserTranslationView.as_view(),
        name="content-topic-conversation-user-translation",
    ),
    path(
        "content/conversation/user-correction",
        ContentTopicConversationUserCorrectionView.as_view(),
        name="content-topic-conversation-user-correction",
    ),
    path("content/topics", ContentTopicsView.as_view(), name="content-topics"),
    path("content/topics/delete", ContentTopicDeleteView.as_view(), name="content-topic-delete"),
    path("content/topic-contexts", ContentTopicContextsView.as_view(), name="content-topic-contexts"),
]
