from django.urls import path

from .views import (
    AuthAdminCreateUserView,
    AuthAIUsageLimitView,
    AuthAIUsageView,
    AuthDeleteUserView,
    AuthBootstrapStatusView,
    AuthGettingStartedCompleteView,
    AuthLoginView,
    AuthLogoutView,
    AuthMeView,
    AuthRegistrationRequestsView,
    AuthRegisterView,
    AuthPinSetupView,
    AuthResetPinView,
    AuthUsersView,
    ContentConfirmView,
    ContentItemActView,
    ContentDialogAudioRegenerateView,
    ContentDialogDetailView,
    ContentDialogTurnAudioView,
    ContentDialogTurnClearAudioView,
    ContentDialogsView,
    ContentItemCompareWordDetailView,
    ContentItemCompareStrategyView,
    ContentItemCompareWordsInsightsView,
    ContentItemCompareWordsSearchView,
    ContentItemCompareWordsView,
    ContentItemRelatedView,
    ContentItemDecodeView,
    ContentItemDetailView,
    ContentItemEncounterView,
    ContentItemExercisesView,
    ContentItemNounExerciseCaseView,
    ContentItemFunnyImageExerciseView,
    ContentItemGrammarExamplesView,
    ContentItemPhraseGrammarFeaturesView,
    ContentItemMarkLearnedView,
    ContentItemPersonalizeView,
    ContentItemPracticeView,
    ContentItemQuestionView,
    ContentItemRegenerateView,
    ContentItemRefreshWordView,
    ContentItemVisualizeView,
    ContentItemWalkView,
    ContentItemsView,
    ContentPhraseQuickAddView,
    ContentPreviewView,
    ContentTopicConversationStartView,
    ContentTopicConversationGoalEvaluationView,
    ContentTopicConversationGoalRegenerateView,
    ContentTopicConversationErrorAnalysisView,
    ContentTopicConversationErrorExercisesView,
    ContentTopicConversationHelpView,
    ContentTopicConversationRealtimeSessionView,
    ContentTopicConversationRealtimeUsageView,
    ContentTopicConversationReviewView,
    ContentTopicConversationTurnView,
    ContentTopicConversationUserCorrectionView,
    ContentTopicConversationUserTranslationView,
    ContentTopicContextsView,
    ContentTopicDeleteView,
    ContentWordQuickAddView,
    ContentTopicsView,
    ContentWordsView,
    CompleteDifficultItemView,
    ElevenLabsVoiceDisableView,
    ElevenLabsVoicePreviewView,
    ElevenLabsVoicesView,
    HealthView,
    LearningProgressPauseView,
    LearningProgressResumeView,
    LearningProgressStudyTimeView,
    LearningProgressView,
    MarkSeenView,
    OverviewStatsView,
    PhraseGrammarPoolView,
    RestoreSessionItemStateView,
    SessionItemPayloadView,
    SessionView,
    SubmitReviewView,
)

urlpatterns = [
    path("health", HealthView.as_view(), name="health"),
    path("auth/login", AuthLoginView.as_view(), name="auth-login"),
    path("auth/bootstrap-status", AuthBootstrapStatusView.as_view(), name="auth-bootstrap-status"),
    path("auth/register", AuthRegisterView.as_view(), name="auth-register"),
    path("auth/pin-setup", AuthPinSetupView.as_view(), name="auth-pin-setup"),
    path("auth/getting-started/complete", AuthGettingStartedCompleteView.as_view(), name="auth-getting-started-complete"),
    path("auth/admin-create", AuthAdminCreateUserView.as_view(), name="auth-admin-create"),
    path("auth/reset-pin", AuthResetPinView.as_view(), name="auth-reset-pin"),
    path("auth/logout", AuthLogoutView.as_view(), name="auth-logout"),
    path("auth/me", AuthMeView.as_view(), name="auth-me"),
    path("auth/registration-requests", AuthRegistrationRequestsView.as_view(), name="auth-registration-requests"),
    path("auth/users", AuthUsersView.as_view(), name="auth-users"),
    path("auth/users/delete", AuthDeleteUserView.as_view(), name="auth-users-delete"),
    path("auth/ai-usage", AuthAIUsageView.as_view(), name="auth-ai-usage"),
    path("auth/ai-usage/limit", AuthAIUsageLimitView.as_view(), name="auth-ai-usage-limit"),
    path("config/elevenlabs-voices", ElevenLabsVoicesView.as_view(), name="config-elevenlabs-voices"),
    path("config/elevenlabs-voices/disable", ElevenLabsVoiceDisableView.as_view(), name="config-elevenlabs-voices-disable"),
    path("config/elevenlabs-voices/preview", ElevenLabsVoicePreviewView.as_view(), name="config-elevenlabs-voices-preview"),
    path("config/phrase-grammar-pool", PhraseGrammarPoolView.as_view(), name="config-phrase-grammar-pool"),
    path("overview-stats", OverviewStatsView.as_view(), name="overview-stats"),
    path("progress", LearningProgressView.as_view(), name="learning-progress"),
    path("progress/study-time", LearningProgressStudyTimeView.as_view(), name="learning-progress-study-time"),
    path("progress/pause", LearningProgressPauseView.as_view(), name="learning-progress-pause"),
    path("progress/resume", LearningProgressResumeView.as_view(), name="learning-progress-resume"),
    path("session", SessionView.as_view(), name="session"),
    path("session/items/<int:item_id>", SessionItemPayloadView.as_view(), name="session-item-payload"),
    path("session/restore-item-state", RestoreSessionItemStateView.as_view(), name="session-restore-item-state"),
    path("review", SubmitReviewView.as_view(), name="review"),
    path("seen", MarkSeenView.as_view(), name="seen"),
    path("difficult-items/complete", CompleteDifficultItemView.as_view(), name="difficult-item-complete"),
    path("content/preview", ContentPreviewView.as_view(), name="content-preview"),
    path("content/confirm", ContentConfirmView.as_view(), name="content-confirm"),
    path("content/dialogs", ContentDialogsView.as_view(), name="content-dialogs"),
    path("content/dialogs/<int:dialog_id>", ContentDialogDetailView.as_view(), name="content-dialog-detail"),
    path("content/dialogs/<int:dialog_id>/audio", ContentDialogAudioRegenerateView.as_view(), name="content-dialog-audio-regenerate"),
    path("content/dialogs/<int:dialog_id>/turns/<int:turn_index>/audio", ContentDialogTurnAudioView.as_view(), name="content-dialog-turn-audio"),
    path("content/dialogs/<int:dialog_id>/turns/<int:turn_index>/clear-audio", ContentDialogTurnClearAudioView.as_view(), name="content-dialog-turn-clear-audio"),
    path("content/items", ContentItemsView.as_view(), name="content-items"),
    path("content/words", ContentWordsView.as_view(), name="content-words"),
    path("content/words/add", ContentWordQuickAddView.as_view(), name="content-word-quick-add"),
    path("content/phrases/add", ContentPhraseQuickAddView.as_view(), name="content-phrase-quick-add"),
    path("content/items/<int:item_id>", ContentItemDetailView.as_view(), name="content-item-detail"),
    path("content/items/<int:item_id>/compare-words", ContentItemCompareWordsView.as_view(), name="content-item-compare-words"),
    path("content/items/<int:item_id>/compare-words/search", ContentItemCompareWordsSearchView.as_view(), name="content-item-compare-words-search"),
    path("content/items/<int:item_id>/compare-words/insights", ContentItemCompareWordsInsightsView.as_view(), name="content-item-compare-words-insights"),
    path("content/items/<int:item_id>/compare-words/<int:linked_item_id>", ContentItemCompareWordDetailView.as_view(), name="content-item-compare-word-detail"),
    path("content/items/<int:item_id>/strategies/compare", ContentItemCompareStrategyView.as_view(), name="content-item-compare-strategy"),
    path("content/items/<int:item_id>/strategies/act", ContentItemActView.as_view(), name="content-item-act"),
    path("content/items/<int:item_id>/strategies/related", ContentItemRelatedView.as_view(), name="content-item-related"),
    path("content/items/<int:item_id>/strategies/decode", ContentItemDecodeView.as_view(), name="content-item-decode"),
    path("content/items/<int:item_id>/strategies/encounter", ContentItemEncounterView.as_view(), name="content-item-encounter"),
    path("content/items/<int:item_id>/strategies/grammar-examples", ContentItemGrammarExamplesView.as_view(), name="content-item-grammar-examples"),
    path("content/items/<int:item_id>/strategies/grammar-features", ContentItemPhraseGrammarFeaturesView.as_view(), name="content-item-phrase-grammar-features"),
    path("content/items/<int:item_id>/exercises", ContentItemExercisesView.as_view(), name="content-item-exercises"),
    path("content/items/<int:item_id>/exercises/noun-case", ContentItemNounExerciseCaseView.as_view(), name="content-item-noun-exercise-case"),
    path("content/items/<int:item_id>/strategies/personalize", ContentItemPersonalizeView.as_view(), name="content-item-personalize"),
    path("content/items/<int:item_id>/strategies/practice", ContentItemPracticeView.as_view(), name="content-item-practice"),
    path("content/items/<int:item_id>/strategies/visualize", ContentItemVisualizeView.as_view(), name="content-item-visualize"),
    path("content/items/<int:item_id>/strategies/walk", ContentItemWalkView.as_view(), name="content-item-walk"),
    path(
        "content/items/<int:item_id>/exercises/funny-image",
        ContentItemFunnyImageExerciseView.as_view(),
        name="content-item-funny-image-exercise",
    ),
    path("content/items/<int:item_id>/mark-learned", ContentItemMarkLearnedView.as_view(), name="content-item-mark-learned"),
    path("content/items/<int:item_id>/regenerate", ContentItemRegenerateView.as_view(), name="content-item-regenerate"),
    path("content/items/<int:item_id>/refresh-word", ContentItemRefreshWordView.as_view(), name="content-item-refresh-word"),
    path("content/items/<int:item_id>/question", ContentItemQuestionView.as_view(), name="content-item-question"),
    path("content/conversation/start", ContentTopicConversationStartView.as_view(), name="content-topic-conversation-start"),
    path("content/conversation/realtime-session", ContentTopicConversationRealtimeSessionView.as_view(), name="content-topic-conversation-realtime-session"),
    path("content/conversation/realtime-usage", ContentTopicConversationRealtimeUsageView.as_view(), name="content-topic-conversation-realtime-usage"),
    path("content/conversation/review", ContentTopicConversationReviewView.as_view(), name="content-topic-conversation-review"),
    path("content/conversation/help", ContentTopicConversationHelpView.as_view(), name="content-topic-conversation-help"),
    path("content/conversation/goal-evaluate", ContentTopicConversationGoalEvaluationView.as_view(), name="content-topic-conversation-goal-evaluate"),
    path("content/conversation/goal-regenerate", ContentTopicConversationGoalRegenerateView.as_view(), name="content-topic-conversation-goal-regenerate"),
    path("content/conversation/error-analysis", ContentTopicConversationErrorAnalysisView.as_view(), name="content-topic-conversation-error-analysis"),
    path("content/conversation/error-exercises", ContentTopicConversationErrorExercisesView.as_view(), name="content-topic-conversation-error-exercises"),
    path("content/conversation/turn", ContentTopicConversationTurnView.as_view(), name="content-topic-conversation-turn"),
    path(
        "content/conversation/user-translation",
        ContentTopicConversationUserTranslationView.as_view(),
        name="content-topic-conversation-user-translation",
    ),
    path(
        "content/conversation/user-correction",
        ContentTopicConversationUserCorrectionView.as_view(),
        name="content-topic-conversation-user-correction",
    ),
    path("content/topics", ContentTopicsView.as_view(), name="content-topics"),
    path("content/topics/delete", ContentTopicDeleteView.as_view(), name="content-topic-delete"),
    path("content/topic-contexts", ContentTopicContextsView.as_view(), name="content-topic-contexts"),
]
